// <auto-generated />
using System;
using AdminCore.Modules.Tenants.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdminCore.Modules.Tenants.Infrastructure.Migrations
{
    [DbContext(typeof(TenantsDbContext))]
    partial class TenantsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenants")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminCore.Modules.Tenants.Domain.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FaviconUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tenants", "tenants");
                });

            modelBuilder.Entity("AdminCore.Modules.Tenants.Domain.Tenant", b =>
                {
                    b.OwnsOne("AdminCore.Modules.Tenants.Domain.TenantTheme", "Theme", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AccentColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PrimaryColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SecondaryColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SurfaceColor")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TenantId");

                            b1.ToTable("Tenants", "tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Theme")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
