/**
 * AdminCore — Frontend Environment Setup
 *
 * Este script gera o arquivo src/environments/environment.ts a partir do .env
 * na raiz do projeto. Execute com: node frontend/setup-env.js
 */

const fs = require('fs');
const path = require('path');

function loadEnv(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  Arquivo .env não encontrado em ${filePath}. Usando defaults.`);
    return env;
  }

  const content = fs.readFileSync(filePath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const idx = trimmed.indexOf('=');
    if (idx <= 0) continue;

    const key = trimmed.substring(0, idx).trim();
    let value = trimmed.substring(idx + 1).trim();

    // Remove surrounding quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    env[key] = value;
  }
  return env;
}

function main() {
  // Find .env by walking up from this script
  let dir = __dirname;
  let envPath = null;
  while (dir !== path.parse(dir).root) {
    const candidate = path.join(dir, '.env');
    if (fs.existsSync(candidate)) {
      envPath = candidate;
      break;
    }
    dir = path.dirname(dir);
  }

  const env = loadEnv(envPath || '');
  const apiUrl = env.FRONTEND_API_URL || 'http://localhost:5000';

  const output = `// Auto-generated by setup-env.js — do not edit manually
export const environment = {
  production: false,
  apiUrl: '${apiUrl}'
};
`;

  const outPath = path.join(__dirname, 'src', 'environments', 'environment.ts');
  fs.writeFileSync(outPath, output, 'utf-8');
  console.log(`✅ Environment gerado: apiUrl=${apiUrl}`);
}

main();
